/**
 * ⚠️  WARNING: AUTO-GENERATED FILE
 * 
 * This file was automatically generated by 🐝 HiveForm.
 * DO NOT EDIT this file manually as your changes will be overwritten.
 * 
 * Generated at: 2025-06-29T09:13:50.506Z
 * 
 * To modify this form:
 * 1. Update your HiveForm component and Field components in your source code
 * 2. The form will be automatically regenerated on next build/save
 * 
 * Learn more: https://github.com/TylerShin/hive-form
 */

import { z } from 'zod';

export type HiveForm1Form = {
  message: string;
  category?: string;
};

export const hiveForm1Schema = z.object({
  message: z.string(),
  category: z.string().optional()
});

export const hiveForm1DefaultValues = {
  message: '',
  category: ''
};

export const hiveForm1Config = {
  type: {} as HiveForm1Form,
  schema: hiveForm1Schema,
  defaultValues: hiveForm1DefaultValues,
  fields: [
  {
    "name": "message",
    "optional": false
  },
  {
    "name": "category",
    "optional": true
  }
]
};