/**
 * ⚠️  WARNING: AUTO-GENERATED FILE
 * 
 * This file was automatically generated by 🐝 HiveForm.
 * DO NOT EDIT this file manually as your changes will be overwritten.
 * 
 * Generated at: 2025-06-29T09:13:50.501Z
 * 
 * To modify this form:
 * 1. Update your HiveForm component and Field components in your source code
 * 2. The form will be automatically regenerated on next build/save
 * 
 * Learn more: https://github.com/TylerShin/hive-form
 */

import { z } from 'zod';

export type LoginForm = {
  email: string;
  password: string;
  confirmPassword: string;
  rememberMe?: string;
  deviceName?: string;
};

export const loginSchema = z.object({
  email: z.string(),
  password: z.string(),
  confirmPassword: z.string(),
  rememberMe: z.string().optional(),
  deviceName: z.string().optional()
});

export const loginDefaultValues = {
  email: '',
  password: '',
  confirmPassword: '',
  rememberMe: '',
  deviceName: ''
};

export const loginConfig = {
  type: {} as LoginForm,
  schema: loginSchema,
  defaultValues: loginDefaultValues,
  fields: [
  {
    "name": "email",
    "optional": false
  },
  {
    "name": "password",
    "optional": false
  },
  {
    "name": "confirmPassword",
    "optional": false
  },
  {
    "name": "rememberMe",
    "optional": true
  },
  {
    "name": "deviceName",
    "optional": true
  }
]
};